# Generated by Django 3.2.9 on 2021-11-09 18:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="link",
            field=models.URLField(null=True, verbose_name="Link"),
        ),
    ]
