# Generated by Django 4.0 on 2022-01-15 21:22

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wishlist", "0002_wish_link"),
    ]

    operations = [
        migrations.CreateModel(
            name="Group",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.TextField(max_length=100)),
                (
                    "users",
                    models.ManyToManyField(
                        related_name="wish_groups", to=settings.AUTH_USER_MODEL
                    ),
                ),
            ],
        ),
    ]
