# Generated by Django 4.1 on 2022-08-26 07:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


def migrate_reservations(apps, schema_editor):
    db_alias = schema_editor.connection.alias
    Wish = apps.get_model("wishlist", "Wish")
    for wish in Wish.objects.using(db_alias).all():
        for reservation in wish.reserved_by.all():
            wish.reserved_by.add(
                wish=reservation.wish, user=reservation.user, quantity=1
            )
            wish.save()


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wishlist", "0004_wish_quantity_alter_wish_owner_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="Wish", old_name="reserved_by", new_name="reserved_by_old"
        ),
        migrations.CreateModel(
            name="Reservation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=1)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "wish",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="wishlist.wish"
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="wish",
            name="reserved_by",
            field=models.ManyToManyField(
                related_name="reserved_wishes",
                to=settings.AUTH_USER_MODEL,
                through="wishlist.reservation",
            ),
        ),
        migrations.RunPython(migrate_reservations),
        migrations.RemoveField(
            model_name="wish",
            name="reserved_by_old",
        ),
    ]
