# Generated by Django 4.1.3 on 2023-05-03 21:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0007_auto_20230425_2208"),
    ]

    operations = [
        migrations.AddField(
            model_name="wish",
            name="favorite",
            field=models.BooleanField(default=False),
        ),
    ]
