# Generated by Django 5.0.6 on 2024-08-06 14:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('wishlist', '0008_wish_favorite'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='wish',
            options={'ordering': ('-favorite',)},
        ),
        migrations.AddField(
            model_name='wish',
            name='depends_on',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL,
                                    related_name='dependent_wishes', to='wishlist.wish'),
        ),
    ]
