# Generated by Django 6.0 on 2025-12-28 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wishlist', '0009_alter_wish_options_wish_depends_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='description',
            field=models.TextField(blank=True, max_length=1000),
        ),
    ]
