repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.2.0
    hooks:
      - id: check-ast
      - id: check-json
      - id: check-yaml
      - id: detect-private-key
      - id: pretty-format-json
        args: [ --autofix ]
      - id: requirements-txt-fixer
#  - repo: https://github.com/pre-commit/mirrors-eslint
#    rev: "v8.15.0"
#    hooks:
#      - id: eslint

  #  - repo: https://github.com/pre-commit/mirrors-mypy
  #    rev: "v0.950"
  #    hooks:
  #      - id: mypy

  - repo: https://github.com/psf/black
    rev: 22.3.0
    hooks:
      - id: black