# Generated by Django 4.1 on 2022-10-30 14:56

import django.core.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("wishlist", "0005_reservation_alter_wish_reserved_by_reservation_wish"),
    ]

    operations = [
        migrations.AlterField(
            model_name="wish",
            name="link",
            field=models.URLField(blank=True, null=True, verbose_name="Link"),
        ),
        migrations.AlterField(
            model_name="wish",
            name="quantity",
            field=models.IntegerField(
                default=1, validators=[django.core.validators.MinValueValidator(1)]
            ),
        ),
        migrations.AlterField(
            model_name="wish",
            name="reserved_by",
            field=models.ManyToManyField(
                related_name="reserved_wishes",
                through="wishlist.Reservation",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
