# Generated by Django 4.1.3 on 2023-04-25 20:08

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("wishlist", "0006_alter_wish_link_alter_wish_quantity_and_more"),
    ]

    operations = [
        migrations.RunSQL("DROP TABLE IF EXISTS wishlist_wish;"),
        migrations.RunSQL("ALTER TABLE app_wish RENAME TO wishlist_wish;"),
        migrations.RunSQL("DROP TABLE IF EXISTS wishlist_group;"),
        migrations.RunSQL("ALTER TABLE app_group RENAME TO wishlist_group;"),
        migrations.RunSQL("DROP TABLE IF EXISTS wishlist_reservation;"),
        migrations.RunSQL(
            "ALTER TABLE app_reservation RENAME TO wishlist_reservation;"
        ),
        migrations.RunSQL("DROP TABLE IF EXISTS wishlist_group_users;"),
        migrations.RunSQL(
            "ALTER TABLE app_group_users RENAME TO wishlist_group_users;"
        ),
        migrations.RunSQL(
            "UPDATE django_migrations SET app = 'wishlist' WHERE app = 'app';"
        ),
        migrations.RunSQL(
            "UPDATE django_content_type SET app_label = 'wishlist' where app_label = 'app';"
        ),
    ]
