# Generated by Django 4.0.6 on 2022-08-21 08:40

from django.conf import settings
from django.db import migrations, models

import app.models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0003_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='wish',
            name='quantity',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wish',
            name='owner',
            field=models.ForeignKey(on_delete=models.SET(app.models.get_sentinel_user), to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='wish',
            name='reserved_by',
        ),
        migrations.AddField(
            model_name='wish',
            name='reserved_by',
            field=models.ManyToManyField(related_name='reserved_wishes', to=settings.AUTH_USER_MODEL),
        ),
    ]
