@startuml

class Wish {
	text: string
	link: URL
	quantity: int
}
Wish "*" --> "1" User: owner
Wish "*" --> "1" User: wish_for >
Wish "*" --> "0..wish.quantity" User: reserved_by >

class Group {
	name: string
}
Group "*" -- "*" User: users >

@enduml